### ISSUE TITLE
error when get json message

### ISSUE THREAD

**Issue by cooltyn** [olliephillips/tinyMQTT#26] opened 2019-08-15 00:52 UTC
When I get json message from server, there is strange first symbols in it, like `{"value":"0.274","mode":0,"preferences":{"hz":100}}`
and the error when trying to JSON.parse() it.
pub.message.slice(2) fixes the problem, but it's not the right way.
In full mqtt module all is ok

**Comment by olliephillips** [comment] 2019-08-15 08:55
Hi thanks reporting. First time I've heard of this.  I'll take a look when I'm next near my ESP8266 stuff - next week or so and update here.

**Comment by olliephillips** [comment] 2019-08-22 14:34
Hello. I can't replicate this. Espruino v2.01, connected to `test.mosquitto.org` broker with the below sketch:

```
let wifi = require("Wifi");
let mqtt = require("https://github.com/olliephillips/tinyMQTT/blob/minify/tinyMQTT.min.js").create("test.mosquitto.org");
let topic = "/esp8226/espruino/op";
if (wifi.getIP().ip != "0.0.0.0") {
  mqtt.connect();  
} else {
  console.log("not connected to Wifi, check saved Wifi config"); 
}

mqtt.on("connected", () => {
  console.log("mqtt broker connected");
  mqtt.subscribe(topic);
});

mqtt.on("message", function(msg){
	console.log(msg.topic);
	console.log(msg.message);
    
    // Parse it
    console.log(JSON.parse(msg.message));

});
```

Transmitting your string (for no reason other than it was handy) from the broker. Console output is:

```
/esp8226/espruino/op
{"value":"0.274","mode":0,"preferences":{"hz":100}}
{
  "value": "0.274",
  "mode": 0,
  "preferences": { "hz": 100 }
 }
```
The module seems to work as expected. Perhaps the issue is with the broker publishing?

**Comment by olliephillips** [comment] 2019-08-22 14:51
Actually I notice I just pulled the wrong branch. So I will have to repeat

**Comment by olliephillips** [comment] 2019-08-22 14:59
It is the same when testing with `master/tinyMQTT.min.js`. I am going to close this issue.

**Closed by olliephillips** 2019-08-22 14:59 UTC
