### ISSUE TITLE
Connected event removes "connected" listeners

### ISSUE THREAD

**Issue by AkosLukacs** [olliephillips/tinyMQTT#20] opened 2019-02-22 14:13 UTC
Hi!

Looks like at [line 79](https://github.com/olliephillips/tinyMQTT/blob/master/tinyMQTT.js#L79) the code `_q.removeAllListeners("connected");` removes all subscribers of the `connected` event. So users have to (re)subscribe after each (re)connection. But other parts of the code does not remove listeners from other events, nor does the "big" MQTT library (as far as I can tell).

It was added in [this commit](https://github.com/olliephillips/tinyMQTT/commit/74370d1ebe41c89251e7fda3f20229e973bf38c9#diff-8bbcea8cef04a070ebbbebb8cc491984R67) and [changed here](https://github.com/olliephillips/tinyMQTT/commit/45bf406b88d1e11453dbc06810cfba998c252c56#diff-8bbcea8cef04a070ebbbebb8cc491984). Any idea why is this behavior different?

Feels like I have a dodgy ESP32 board, because I have all kinds of wifi connection issues, but that means I can stress test the tinyMQTT library with all kinds of dis- and re-connections :)

**Comment by olliephillips** [comment] 2019-02-22 17:12
Too far back to say, TBH, and my commit messages aren't that helpful :/
Without this what is the impact on ```process.memory()```?  Many of the tweaks I made back when I was using this library quite intensively, saught to recover memory, or prevent leaks, in the event of unreliable connections. I would guess this was one such tweak.

**Comment by AkosLukacs** [comment] 2019-02-23 10:05
Tried to do some measurements, but looks like I have a memory leak with the latest tinyMQTT, but no leak with MQTT. Here is [my code](https://gist.github.com/AkosLukacs/63819f47eedcafe7c57c59be46fd2c04). The wifi reconnect part feels like a mess :/ 
Basically connect to mqtt, subscribe just for fun, and post memory usage every 2 seconds. Startup usage: 543 and 394 vars.

Calling `mqtt.disconnect()` with tinyMQTT, or a spontaneous wifi disconnect increases memory usage consistently.
Calling `mqtt.disconnect()` with full MQTT, there is only a tiny spike, but there is no visible leak. Looks like there is some leak on real wifi connection loss.

Plotted the memory usage with grafana, and here is it:
![image](https://user-images.githubusercontent.com/844331/53284778-20000500-3759-11e9-86f0-7a5215d3aaaa.png)

While writing, I had a wifi hiccup: +20 vars for MQTT, +92 vars for tinyMQTT
![image](https://user-images.githubusercontent.com/844331/53284868-3064af80-375a-11e9-9b2e-7ec6f08793ac.png)

![image](https://user-images.githubusercontent.com/844331/53284863-22169380-375a-11e9-91d0-a8a7e1e288ae.png)

But issuing a `clearInterval()` + `setInterval(measure, MEASURE_INTERVAL_SECONDS*1000);`, reduced the memory usage to original +4 vars (I guess history).

Meh, diagnosing and debugging random disconnects is fun :)

**Comment by olliephillips** [comment] 2019-02-23 10:18
Ok. I can’t look at this at moment, but there appears to be an issue, yes. It’s odd as there was some really extensive testing done recently on ESP8266 by a contributor which tested all kinds of disconnect reconnect scenarios it was a thumbs up.  I will post his username so he is aware of this issue too.  Out of interest, do you only have ESP32?  I don’t have one, so can’t test like for like, and I would like to rule out it being a problem specific to that build. Do you have an ESP8266?

**Comment by olliephillips** [comment] 2019-02-23 10:22
@MaBecker FYI, maybe you can fire up your test rig again ;)

**Comment by AkosLukacs** [comment] 2019-02-24 13:03
Some info: I do have two ESP8266s running for over two weeks (sending temperature, humidity and free memory thru MQTT). Looking at the free memory graph, there were 3 memory leaks (99% Wifi connection lost, because free memory decreased at the same time for both devices). In those cases, memory change was -71 free vars. Otherwise they are fine.

Did some testing with the ESP32 and some tin foil :)
(sorry for this wall of text, not directly related, but might be useful) I thought it would let me test Wifi disconnects, but it's not that easy. Lightly wrapping it yielded -88 ~ -93 RSSI, no wifi or MQTT disconnect event for some time, but stopped the actual communication.
The ESP's reaction is not conclusive: No Wifi disconnected event at all.

Sometimes I got an MQTT disconnected event, sometimes I got this exception:
```
Uncaught InternalError: Unable to locate host
  at line 1 col 85
...t({host:a.svr,port:a.prt},b)
                                        ^
in function called from system
```
And the console kind-of hangs. I can type commands, but they appear only after a couple of seconds. I guess trying to do some network stuff...

**Comment by olliephillips** [comment] 2019-02-25 11:15
Thanks for all this info and your testing.  It will be a week or so before I can get hands on again with tinyMQTT and ESP2366 pub/sub environment. I recall wifi outage being problematic to test. The main focus of the reconnect is where the broker disconnects - as is frequently the case on the free test brokers such as test.mosquitto.org and iot.eclipse.org. This seems easy enough to recover from without losing memory. I won't be able to on ESP32 testing as I don't have one.

**Comment by AkosLukacs** [comment] 2019-02-26 13:03
Hi, no worries!
The previous test you are refering to #13 by @MaBecker? I have a spare ESP8266 and ESP32, so can compare how they behave.
The ESP32 is just the edge of the wifi range, I guess that's why that gets more wifi disconnects than my ESP8266 boards.

**Comment by olliephillips** [comment] 2019-03-07 17:10
> The previous test you are refering to #13 by @MaBecker? I have a spare ESP8266 and ESP32, so can compare how they behave.

Sorry tardy reply. Yes that one. He seemed to test all sorts of reconnects in a fairly complex test setup (by my standards) and reported all good.  There have been no material changes to the library since then.

**Comment by olliephillips** [comment] 2019-03-07 21:28
I've managed to do a little testing tonight, it loses memory on disconnect/reconnect.  This must be a regression, as i'm certain it could connect/reconnect with no loss at one time. In fact, randomly I picked an earlier commit. This would seem to work with no jsvar loss on disconnect/reconnect?  It does for me

```https://raw.githubusercontent.com/olliephillips/tinyMQTT/e13f121eb08524bdcaaa050d6ca9b165062f3f3f/tinyMQTT.js```

Test code

```
  // assumes wifi config is saved for automatic connections
  let wifi = require("Wifi");
  let mqtt = require("tinyMQTT").create("iot.eclipse.org");
  let topic = "/esp8266/espruin/opp";
  let payload = "";  
  let pubInterval = 2000;
  let disInterval = 30000;
  let mqttConn = false;
  
  wifi.stopAP();

  console.log("connecting");

  if (wifi.getIP().ip !== "0.0.0.0") {
    console.log("wifi connected");
    mqtt.connect();
  } 

  mqtt.on("connected", () => {
    console.log("mqtt connected");
    if (mqttConn === false) {
      mqtt.publish(topic, "connected");
      mqttConn = true;
    }
    
    setInterval(() => {
      payload = JSON.stringify(process.memory());
      mqtt.publish(topic, payload);
    }, pubInterval);
  });

  setInterval(() => {
    mqtt.disconnect();
  }, disInterval);

  mqtt.on("disconnected", () => {
    console.log("mqtt disconnnected");
    mqttConn = false;
    mqtt.connect();
  });

```
I'll pick this up as and when I can, but on the face it this seems reliable, whereas the latest commit is not.

**Comment by olliephillips** [comment] 2019-03-08 17:20
Logging findings after some further basic testing:

1)  latest commit loses memory on client initiated disconnect/reconnect, but will recover from a broker initiated disconnect (memory impact not recorded)
2) commit mentioned above, does not lose memory on client initiated disconnect/reconnect, but does not recover from a broker initiated disconnect at all, publishing ceases.

Wifi outage is another dimension, and I've not tested yet.

**Comment by MaBecker** [comment] 2019-03-08 17:23
Hi @olliephillips 

back to run some tests if needed, just let me know.

**Comment by AkosLukacs** [comment] 2019-03-08 17:28
Thanks for the testing!
I have a hunch, but can't get my code running to test it....
Looks like this [setInterval](https://github.com/olliephillips/tinyMQTT/blob/master/tinyMQTT.js#L68) is not canceled on disconnect. Probably that leaks some memory.

**Comment by olliephillips** [comment] 2019-03-08 17:36
Hey @MaBecker - if you're able to that would help enormously. Did you log any results from your previous test rig? I thought we had a stable library after your testing!

A synopis, maybe a basis for tests (@AkosLukacs jump in anything amiss with my thinking)

- Current library does not recover well from wifi loss. Untested by myself so far
- Code in current library (removeAllListeners) impacts the event handling, to the detriment of it
- Current library, loses jsvars when client disconnects and reconnects, but can recover from broker disconnect events (in my testing)
- Older versions (see commit) will recover from client dis/connects with no jsvar loss, but simply, fall over when broker goes off line

I suspect in pursuing stablity when I broker flakes out, I've introduced the issue where the client loses memory when disconnecting.  And I've just seen that @AkosLukacs has commented while i've been writing this.

**Comment by olliephillips** [comment] 2019-03-08 17:39
@AkosLukacs if you have working code, I'm happy to run it over weekend, I will have some time and have a device to hand.

**Comment by AkosLukacs** [comment] 2019-03-08 18:09
I think I have something better:
![image](https://user-images.githubusercontent.com/844331/54046452-a21a1000-41d4-11e9-896f-e7a9296f83e5.png)

Added two clearIntervals, so a manual disconnect does not leak memory. I will try what happens if I shut down the mqtt broker.
Tested on local PI, just can't connect to iot.eclipse.org. 😕

**Comment by MaBecker** [comment] 2019-03-08 18:13
This is what I used in my tests:

[test_code_for_tinyMQTT.js.txt](https://github.com/olliephillips/tinyMQTT/files/2946954/test_code_for_tinyMQTT.js.txt)
[tinyMQTT.min.js.txt](https://github.com/olliephillips/tinyMQTT/files/2946956/tinyMQTT.min.js.txt)

**Comment by olliephillips** [comment] 2019-03-08 18:14
I will check that PR out - thanks!
Re iot.eclipse.org - yes, it's been offline most of the day for me too, but interested in your broker disconnect findings when you have them. Thanks again.

**Comment by AkosLukacs** [comment] 2019-03-08 18:16
Looks like no problems with broker disconnect:
![image](https://user-images.githubusercontent.com/844331/54047109-7566f800-41d6-11e9-9529-0e0de2506a5a.png)

The disconnects are me killing mosquitto. Reconnects automatically in a few seconds after mosquitto is restarted.

Time to kill the wifi :)

**Comment by olliephillips** [comment] 2019-03-08 18:19
> This is what I used in my tests:
> 
> [test_code_for_tinyMQTT.js.txt](https://github.com/olliephillips/tinyMQTT/files/2946954/test_code_for_tinyMQTT.js.txt)
> [tinyMQTT.min.js.txt](https://github.com/olliephillips/tinyMQTT/files/2946956/tinyMQTT.min.js.txt)

Looks like you had client disconnects in there (and reboots!!).  I'm throughly confused now. This was stable for you? The only immediate difference I can see is that you reconnect inline, and not via the "disconnect" event handler as per my testing.

**Comment by olliephillips** [comment] 2019-03-08 18:54
@AkosLukacs I checked out your amended code and ran it for a bit:

Client dis/connect - works, no leak
Broker dis/connect - works, no leak, published resumes.
1.5 Kb minfied.

Appreciate that wifi outage untested, but will merge your PR tomorrow - it stablises tinyMQTT - so thanks again :)

**Comment by AkosLukacs** [comment] 2019-03-08 19:17
Some wifi testing. The crazy thing is, putting it in a steel pot + covering it is not enough to reliably kill wifi connection 😱 Needed some anti-static bag...


Green is the memory usage, yelow-orange is RSSI. If you zoom in, you can see the points where the mqtt broker received data, and you can see some missing points.

Case 1: spotty wifi, but the ESP8266 still thinks it's connected -> connection resumed quickly, temporary memory usage increase, but memory usage returns to previous state:
![image](https://user-images.githubusercontent.com/844331/54049755-b0b8f500-41dd-11e9-86a2-a4e088058f33.png)

Case 2: ESP8266 wifi actually disconnects -> connection is resumed, altho a bit slower. Memory usage did increase permanently after reconnect. 
![image](https://user-images.githubusercontent.com/844331/54049920-389eff00-41de-11e9-8260-74f09b667fce.png)
Not yet sure if the origin of the leak is tinyMQTT, wifi or user code.

The console error messages during wifi connection loss (sorry, can't copy the text from the IDE for some reason):
![image](https://user-images.githubusercontent.com/844331/54050077-992e3c00-41de-11e9-8083-32c88289ffd4.png)

**Comment by olliephillips** [comment] 2019-03-08 19:17
PR #21 has rectified the immediate problems. But rather than close, I relabelled this. If wifi outage is now stable that would be a major plus. I will attempt some testing myself over weekend.

**Comment by olliephillips** [comment] 2019-03-08 19:34
Can we use `wifi.disconnect()` here to simulate? I get that it is client initiated, so we are left in a better state in terms of clean up than with a proper outage, but that might help isolate it to library, net or wifi?

**Comment by AkosLukacs** [comment] 2019-03-08 20:29
Maybe, so far looks like can't connect back to wifi after a disconnect. It just stays in `connecting` state, or an `auth_expire` or other error in the callback. Maybe the ESP8266 or my router doesn't like reconnections? Tried manually calling disconnect and waiting a minute or so, but no luck so far...

**Comment by olliephillips** [comment] 2019-03-09 05:08
I see same I think. Take tinyMQTT out the equation and can connect and disconnect from Wifi no issue.  Add it back by connecting to the broker and after first Wifi connect/disconnect there are no further attempts - nothing is logged to console either (wifi connecting), and I don't get the mqtt disconnect event handled first time around (mqtt disconnected). 

So either the library or the net module?

This is the test code: 

```
let wifi = require("Wifi");
let mqtt = require("pr032019").create("192.168.1.64");
let topic = "/esp8266op/espruino";
let tO;

wifi.disconnect();

if (wifi.getIP().ip === "0.0.0.0") { 
  setInterval(() => {
    console.log("wifi connecting");
    wifi.connect("ssid", {password:"xxxxxxx"}, function(){ 
     // comment the two lines below out and wifi connects, disconnects and reconnects
      console.log("mqtt connecting");
      mqtt.connect();
    });
  }, 40000);
  
  wifi.on('connected', () => { 
    console.log("wifi connected");
     tO = setTimeout(() => {
      wifi.disconnect();
    },10000);
  });
  
  wifi.on('disconnected', () => { 
    console.log("wifi disconnected");
    clearTimeout(tO);
  });
  
  mqtt.on("connected", () => {
    console.log("mqtt connected");
    payload = JSON.stringify(process.memory());
    mqtt.publish(topic, payload);
  });
 
  mqtt.on("disconnected", () => {
    console.log("mqtt disconnected");
  });
  
}
```

**Comment by MaBecker** [comment] 2019-03-09 08:27
sorry this was the code I used for testing
[code_tinyMQTT_NEW.js.txt](https://github.com/olliephillips/tinyMQTT/files/2948211/code_tinyMQTT_NEW.js.txt)

**Comment by MaBecker** [comment] 2019-03-10 12:15
Wow, some `clearInval` inside pr032019 is killing the tests intervals from code_tinyMQTT_NEW.js.txt


```
	TMQ.prototype.connect = function(){
		var onConnected = function() {
			clearInterval(this.con);
			console.log("clearInterval this.con:", this.con);

```

```
Calculating Size...
Writing..
CRunning onInit()...
clearInterval this.con: undefined
> 

```

fix: do not use clearInterval if parameter is not defined because this will kill all intervals ;-)

my work around: start my intervals after 5sex

**Comment by AkosLukacs** [comment] 2019-03-10 12:21
@MaBecker ooooooooooops, you are absolutely right. should check before both `clearInterval`s...

**Comment by MaBecker** [comment] 2019-03-10 17:20
Fist finding:

- disconnect works fine
- connect after disconnect is the leak , nearly 70var for each reconnect

```
Espruino/tinyMQTT/212011-362B {"ts":"Sun Mar 10 2019 15:09:31 GMT+0100","id":"21204A-B121","info":"{"i":"hello"}"}
Espruino/tinyMQTT/212011-362B {"ts":"Sun Mar 10 2019 15:09:36 GMT+0100","id":"21204A-B121","info":"pmf:1056"}
Espruino/tinyMQTT/212011-362B {"ts":"Sun Mar 10 2019 15:09:41 GMT+0100","id":"21204A-B121","info":"pmf:1056"}
Espruino/tinyMQTT/212011-362B {"ts":"Sun Mar 10 2019 15:09:46 GMT+0100","id":"21204A-B121","info":"pmf:1058"}
Espruino/tinyMQTT/212011-362B {"ts":"Sun Mar 10 2019 15:09:46 GMT+0100","id":"21204A-B121","info":"{"i":"hello"}"}
Espruino/tinyMQTT/all {"ts":"Sun Mar 10 2019 15:09:46 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/212011-362B {"ts":"Sun Mar 10 2019 15:09:51 GMT+0100","id":"21204A-B121","info":"pmf:985"}
Espruino/tinyMQTT/212011-362B {"ts":"Sun Mar 10 2019 15:09:56 GMT+0100","id":"21204A-B121","info":"pmf:985"}
Espruino/tinyMQTT/212011-362B {"ts":"Sun Mar 10 2019 15:10:01 GMT+0100","id":"21204A-B121","info":"pmf:986"}
Espruino/tinyMQTT/212011-362B {"ts":"Sun Mar 10 2019 15:10:01 GMT+0100","id":"21204A-B121","info":"{"i":"hello"}"}

```

**Comment by MaBecker** [comment] 2019-03-10 17:29
There is no memory leak in module MQTT, just tested.

**Comment by MaBecker** [comment] 2019-03-10 18:06
@olliephillips the memory leak exists in very version.

**Comment by olliephillips** [comment] 2019-03-10 18:10
Not had much time unfortunately (best laid plans). I can see with PR032019 (latest) that the intervals get cancelled. I didn't pick up on this in my testing last week, the code as I recall ran perfectlty. It probably impact my subsequent wifi disconnect tests as callback code not running could have been an issue. 

In retestng now I also can confirm that a client disconnect (keyed to console now) disconnects and reconnects and I lose NO memory. I can also confirm the same is true when the broker goes offline and comes back.  @mabecker if you run with PR032019 and initiate disconnect in console, does it resume on the sme memory? So we are in a decent place, but need to address the interval cancellation - and hope that, that is not crucial to conserving memory as @maBecker your tests might indicate - since you made a workaround for it.

If we are to prolong testing can we agree a common (simple script), I lterally have access to one ESP8266 a local MQTT broker and obviously the free remote ones at the moment - don't ask.

**Comment by olliephillips** [comment] 2019-03-10 18:18
> There is no memory leak in module MQTT, just tested.

You can go back, and find a commit that doesn't - I did, but that had a whole rake of problems with the broker disconnecting, so is best left where it is. I think I ruined manual disconnect/reconnect when trying to improve resilience to server disconnects.

Try the latest, but try manually disconnecting. In my testing just now, this comes right back (if you mqtt.connect in the disconnect handler) with no loss whatsoever and same applies if the broker goes offline and comes back.  I

**Comment by AkosLukacs** [comment] 2019-03-10 18:38
I fixed the interval clearing, sorry for that. I have a blinking led for that now :)
And wrapping some socket write calls in try-catch seems to solve memory leaks in edge-cases: Like unreliable wifi, real wifi disconnects, broker going down. I think the real world tinfoil test uncovered some issues you would think not possible. Like [socket write just after the socket connected event](https://github.com/olliephillips/tinyMQTT/blob/master/tinyMQTT.js#L66) threw exception.

Oh, and looks like cleaning up sockets also solves the ESP-can't-reconnect-to-wifi issue!

Doing some more testing, current version (with some debug prints) is [here](https://gist.github.com/AkosLukacs/91eb66ca26590c0cc1b9fe249764d606).

**Comment by olliephillips** [comment] 2019-03-10 19:02
Quickly revised my code as my intervals where stacking up and causing some issue in memory logging. For me this new version runs without problem. All interval callbacks honoured, no leak on client disconnect/reconnect (programmatically, or done manual in console) and no leak when the broker goes offline and comes back.

**Comment by olliephillips** [comment] 2019-03-10 19:03
Thanks @AkosLukacs & @MaBecker for your efforts on this. Appreciated

**Comment by olliephillips** [comment] 2019-03-10 19:08
This was my test code, probably a bit scruffy:

```
// assumes wifi config is saved for automatic connections
  let wifi = require("Wifi");
  let mqtt = require("pr032019").create("192.168.1.64"); // latest @AkosLukacs code
  let topic = "/esp8266/espruin/opp";
  let payload = "";  
  let pubInterval = 2000;
  let disInterval = 30000;

  let disT;
  let connT;

  wifi.stopAP();

  console.log("connecting");

  if (wifi.getIP().ip !== "0.0.0.0") {
    console.log("wifi connected");
    mqtt.connect();
  } 

  mqtt.on("connected", () => {
    console.log("mqtt connected");

    if (disT) {
      clearInterval(disT);
    }
    

      mqtt.publish(topic, "connected");
     

    
    connT = setInterval(() => {
      payload = JSON.stringify(process.memory());
      mqtt.publish(topic, payload);
    }, pubInterval);
    
      disT = setInterval(() => {
    mqtt.disconnect();
  }, disInterval);
    
  });



  mqtt.on("disconnected", () => {
    console.log("mqtt disconnnected");
    if(connT){
      clearInterval(connT);
    }

    mqtt.connect();
  });

```

**Comment by olliephillips** [comment] 2019-03-10 19:32
Also some really quick testing with manual wifi disconnects and reconnects. Seems good. The event callbacks all fire, MQTT publishing resumes on wifi reconnection. Memory use seems stable. Script tested:

```
let wifi = require("Wifi");
let mqtt = require("pr032019").create("192.168.1.64");
let topic = "/esp8266/espruin/opp";
let tO;

wifi.disconnect();

if (wifi.getIP().ip === "0.0.0.0") { 
  setInterval(() => {
    console.log("wifi connecting");
    wifi.connect("", {password:""});
  },40000);
  

  wifi.on('connected', () => { 
    console.log("wifi connected");
    console.log("mqtt connecting");
      mqtt.connect();
     tO = setTimeout(() => {
      wifi.disconnect();
    },20000);
  });
  
  wifi.on('disconnected', () => { 
    console.log("wifi disconnected");
    clearTimeout(tO);
  });
  
  mqtt.on("connected", () => {
    console.log("mqtt connected");
    payload = JSON.stringify(process.memory());
    mqtt.publish(topic, payload);
  });
 
  mqtt.on("disconnected", () => {
    console.log("mqtt disconnected");
  });
  
}
```

**Comment by AkosLukacs** [comment] 2019-03-10 20:26
The cleaned up code is in the pull, please check it out.

**Comment by MaBecker** [comment] 2019-03-11 00:49
> The cleaned up code is in the pull, please check it out.

Yes, intervals and memory leak is fixed - thanks.

```
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:36:20 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:36:21 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:36:26 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:36:31 GMT+0100","id":"21204A-B121","info":"pmf:966"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:36:31 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:36:35 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:36:36 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:36:41 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:36:46 GMT+0100","id":"21204A-B121","info":"pmf:966"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:36:46 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:36:50 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:36:51 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:36:56 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:01 GMT+0100","id":"21204A-B121","info":"pmf:966"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:37:01 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:37:05 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:06 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:11 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:16 GMT+0100","id":"21204A-B121","info":"pmf:966"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:37:16 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:37:20 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:21 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:26 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:31 GMT+0100","id":"21204A-B121","info":"pmf:966"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:37:31 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 01:37:35 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:36 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:41 GMT+0100","id":"21204A-B121","info":"pmf:965"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 01:37:46 GMT+0100","id":"21204A-B121","info":"pmf:966"}
```

**Comment by MaBecker** [comment] 2019-03-11 01:53
Running tinyMQTT from storage saves about 100 vars (1071 versus 966 )

```
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:47:20 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:47:20 GMT+0100","id":"21204A-B121","info":"pmf:1072"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:47:25 GMT+0100","id":"21204A-B121","info":"pmf:1072"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:47:30 GMT+0100","id":"21204A-B121","info":"pmf:1073"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:47:30 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:47:34 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:47:35 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:47:40 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:47:45 GMT+0100","id":"21204A-B121","info":"pmf:1071"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:47:45 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:47:50 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:47:50 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:47:55 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:48:00 GMT+0100","id":"21204A-B121","info":"pmf:1071"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:48:00 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:48:05 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:48:05 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:48:10 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:48:15 GMT+0100","id":"21204A-B121","info":"pmf:1071"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:48:15 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:48:20 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:48:20 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:48:25 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:48:30 GMT+0100","id":"21204A-B121","info":"pmf:1071"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:48:30 GMT+0100","id":"21204A-B121","info":"disconnect"}
Espruino/tinyMQTT/all {"ts":"Mon Mar 11 2019 02:48:35 GMT+0100","id":"21204A-B121","info":"connected"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:48:35 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
Espruino/tinyMQTT/212011-362B {"ts":"Mon Mar 11 2019 02:48:40 GMT+0100","id":"21204A-B121","info":"pmf:1070"}
```

**Comment by olliephillips** [comment] 2019-03-11 09:43
Library is now in great shape, thanks again guys. 
Latest PR merged and @MaBecker if we can figure out how to get this running from storage without breaking it for non storage users, more than happy include. That's a respectable saving on memory that could be useful with some more complex Espruino sketches. Closing this

**Closed by olliephillips** 2019-03-11 09:43 UTC
Labels: enhancement

**Comment by AkosLukacs** [comment] 2019-03-11 09:51
Glad to help!

@MaBecker did you try memory usage with the Espruino IDE's "Modules uploaded as functions (BETA)"?

**Comment by MaBecker** [comment] 2019-03-11 15:10
> @MaBecker did you try memory usage with the Espruino IDE's "Modules uploaded as functions (BETA)"?

@AkosLukacs This is not the same, because it is note written to flash 

`require('Storage').write('tinyMQTS','{.........}();'`

and after that  you can use it like this

`mqtt = require('tinyMQTS')`

**Comment by MaBecker** [comment] 2019-03-11 15:27
> Latest PR merged and @MaBecker if we can figure out how to get this running from storage without breaking it for non storage users, more than happy include. That's a respectable saving on memory that could be useful with some more complex Espruino sketches.

No had to make manual changes to it.  

* Minify uses "" for strings, so switch everything  to double quotes

* change `"\x00"` to `"\\0x00"`

and you get [load_tinyMQTT_to_Storage.js.txt](https://github.com/olliephillips/tinyMQTT/files/2952894/load_tinyMQTT_to_Storage.js.txt)

**Comment by olliephillips** [comment] 2019-03-11 15:56
> 
> No had to make manual changes to it.
> 
> * Minify uses "" for strings, so switch everything  to double quotes
> * change `"\x00"` to `"\\0x00"`

@MaBecker - so the escaping needs to be implemented as "\\0x00" instead of "\\x00". In the last PR I think we had the latter style. So if we use the former escaping ("\\0x00"), you're saying the module is good for both storage and non-storage use?  As you recall, I had to revert that PR because it silently died after 30 or so seconds, when not loaded from storage.

**Comment by MaBecker** [comment] 2019-03-11 16:04
Oh now, wanted to write

* change "\x00" to "\\\x00"

check  the uploaded file.

**Comment by MaBecker** [comment] 2019-03-11 16:07
Hint: Do not use "\\\x00" for uploading a required module with WebIDE

This is only needed when loading from storage, I have no clue why this is need ......

**Comment by MaBecker** [comment] 2019-03-11 16:20
We could try to use String.fromCharCode(0)

**Comment by MaBecker** [comment] 2019-03-11 16:51
Replace \\\x00 with sFcc(0) and it works via upload and storage

**Comment by MaBecker** [comment] 2019-03-11 16:53
[store_module_tinyMQTT.js.txt](https://github.com/olliephillips/tinyMQTT/files/2953333/store_module_tinyMQTT.js.txt)

**Comment by olliephillips** [comment] 2019-03-11 17:14
Ok thanks @MaBecker that's an interesting angle - I can't look at now, but will pick up this and the other <256 byte receive suggestion in the next few days with a view to modifying library for both
